## VM setup

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%cd "/content/gdrive/MyDrive/Master Thesis/Language Model Training"

/content/gdrive/MyDrive/Master Thesis/Language Model Training


In [3]:
!pip install transformers==4.17

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 3.8 MB 5.1 MB/s 
     |████████████████████████████████| 6.6 MB 56.3 MB/s 
     |████████████████████████████████| 880 kB 51.2 MB/s 
     |████████████████████████████████| 120 kB 53.8 MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=f7ac207cb2814eeaea4056887442e9849de7cd5e9fd2196dc3ff512d16990c3d
  Stored in directory: /root/.cache/pip/wheels/87/39/dd/a83eeef36d0bf98e7a4d1933a4ad2d660295a40613079bafc9
Successfully built sacremoses


In [4]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 365 kB 5.0 MB/s 
     |████████████████████████████████| 212 kB 67.5 MB/s 
     |████████████████████████████████| 115 kB 53.5 MB/s 
     |████████████████████████████████| 127 kB 67.8 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [5]:
!pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 69 kB 3.9 MB/s 


In [6]:
!mkdir /tmp/software/
!mkdir /tmp/software/git/
!wget https://github.com/git-lfs/git-lfs/releases/download/v3.2.0/git-lfs-linux-amd64-v3.2.0.tar.gz -P /tmp/software/git/
!tar -xzf /tmp/software/git/git-lfs-linux-amd64-v3.2.0.tar.gz -C /tmp/software/git/
!bash /tmp/software/git/git-lfs-3.2.0/install.sh
!git lfs install
!git lfs --version
%cd

--2022-08-25 12:03:24--  https://github.com/git-lfs/git-lfs/releases/download/v3.2.0/git-lfs-linux-amd64-v3.2.0.tar.gz
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/13021798/a54487ef-9c78-4334-aff1-690923745d5c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220825%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220825T120324Z&X-Amz-Expires=300&X-Amz-Signature=f81e8313f6237a694db569f95fa4b2a2d2392bc2cacc64e4912772729e69103e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=13021798&response-content-disposition=attachment%3B%20filename%3Dgit-lfs-linux-amd64-v3.2.0.tar.gz&response-content-type=application%2Foctet-stream [following]
--2022-08-25 12:03:24--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/13021798/a54487ef-9c78

## Download git repo from github

In [7]:
!bash "/content/gdrive/MyDrive/Master Thesis/Data/clone_repo.sh"

Cloning into '/content/experiments_chd'...
remote: Enumerating objects: 1249, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1249 (delta 41), reused 48 (delta 35), pack-reused 1189
Receiving objects: 100% (1249/1249), 146.20 KiB | 459.00 KiB/s, done.
Resolving deltas: 100% (799/799), done.


In [8]:
%cd /content/experiments_chd

/content/experiments_chd


In [9]:
!git checkout testing_epochs

Branch 'testing_epochs' set up to track remote branch 'testing_epochs' from 'origin'.
Switched to a new branch 'testing_epochs'


In [10]:
!bash "/content/gdrive/MyDrive/Master Thesis/Data/pull_repo.sh"

Already up to date.


In [11]:
%cd

/root


## Imports

In [12]:
import sys
sys.path.insert(0, "/content/gdrive/MyDrive/Master Thesis/ModelFineTuning/")
sys.path.insert(0, "/content/experiments_chd/model_finetuning/TransformerPlusTemporal/")
from hub_token import HUB_TOKEN

In [13]:
import torch
from torch import cuda
import transformers
from transformers import RobertaModel, RobertaForSequenceClassification
from LanguageModelPlusTemporal import LanguageModelPlusTemporal
from transformers import RobertaTokenizerFast
from transformers import TrainerCallback
import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from scipy.stats import pearsonr

from collections import ChainMap
import random
from tqdm import tqdm
import shutil
from datetime import datetime
import json
import os
import evaluate

In [14]:
import multiprocessing

core_count = multiprocessing.cpu_count() # Count the number of cores in a computer
core_count

2

In [15]:
device = 'cuda' if cuda.is_available() else 'cpu'
device

'cuda'

## Models

In [16]:
def sigmoid(a):
  return 1/(1 + np.exp(-a))

In [17]:
def softmax(a):
  return np.exp(a)/np.sum(np.exp(a))

In [32]:
models_datasets = {
    "TwitchLeagueBert-500k-likefu":{
        "model_name": "Epidot/TwitchLeagueBert-500k-finetuned-highlight-detection",
        "dataset_name": "Epidot/private_fuetal2017_TwitchLeagueBert_highlights_preprocessed_oversampled",
        "activation_function": sigmoid
    },
    "TwitchLeagueBert-500k-temporal":{
        "model_name": "Epidot/TwitchLeagueBert-500k-finetuned-highlight-detection-plus-temporal",
        "dataset_name": "Epidot/private_fuetal2017_highlights_temporal_preprocessed_TwitchLeagueBert_oversampled",
        "activation_function": sigmoid
    },
    "TwitchLeagueBert-1000k-likefu": {
        "model_name": "Epidot/TwitchLeagueBert-1000k-finetuned-highlight-detection",
        "dataset_name": "Epidot/private_fuetal2017_TwitchLeagueBert_highlights_preprocessed_oversampled",
        "activation_function": sigmoid
    },
    "TwitchLeagueBert-1000k-temporal":{
        "model_name": "Epidot/TwitchLeagueBert-1000k-finetuned-highlight-detection-plus-temporal",
        "dataset_name": "Epidot/private_fuetal2017_highlights_temporal_preprocessed_TwitchLeagueBert_oversampled",
        "activation_function": sigmoid
    },
    "TwitchLeagueBert-1000k-temporal-structure":{
        "model_name": "Epidot/TwitchLeagueBert-1000k-finetuned-highlight-detection-plus-temporal-epochs",
        "dataset_name": "Epidot/private_fuetal2017_highlights_temporal_preprocessed_TwitchLeagueBert-1000k_oversampled",
        "activation_function": sigmoid
    },
      "TwitchLeagueBert-500k-temporal-structure":{
        "model_name": "Epidot/TwitchLeagueBert-500k-finetuned-highlight-detection-plus-temporal-epochs",
        "dataset_name": "Epidot/private_fuetal2017_highlights_temporal_preprocessed_TwitchLeagueBert_oversampled",
        "activation_function": sigmoid
    },
    "Roberta-like-fu":{
        "model_name": "Epidot/roberta-base-finetuned-highlight-detection",
        "dataset_name": "Epidot/private_fuetal2017_highlights_preprocessed_oversampled",
        "activation_function": sigmoid
    },
    "Roberta-temporal":{
        "model_name": "Epidot/roberta-base-finetuned-highlight-detection-plus-temporal",
        "dataset_name": "Epidot/private_fuetal2017_highlights_temporal_preprocessed_roberta-base_oversampled",
        "activation_function": sigmoid
    },
    "Roberta-temporal-structure":{
        "model_name": "Epidot/roberta-base-finetuned-highlight-detection-plus-temporal-epochs",
        "dataset_name": "Epidot/private_fuetal2017_highlights_temporal_preprocessed_roberta-base_oversampled",
        "activation_function": sigmoid
    }
}

## Loading non-huggingface models

In [35]:
m_name = "TwitchLeagueBert-1000k-temporal-structure" # "Roberta-temporal-structure"
lm_path = "Epidot/TwitchLeagueBert-1000k"  # roberta-base, Epidot/TwitchLeagueBert-1000k
m = models_datasets[m_name]

In [36]:
!rm -r /tmp/models
!mkdir /tmp/models
%cd /tmp/models
!git clone https://huggingface.co/{m["model_name"]}
%cd

/tmp/models
Cloning into 'TwitchLeagueBert-1000k-finetuned-highlight-detection-plus-temporal-epochs'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 32 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (32/32), done.
/root


In [37]:
from sklearn.base import TransformerMixin
model_state_dict = torch.load(f"/tmp/models/{m['model_name'].split('/')[-1]}/pytorch_model.bin")
model_training_args ={
    "lm_path": lm_path, # roberta-base, Epidot/TwitchLeagueBert-1000k
    "window_size": 2,
    "num_dist_steps": None,
    "num_dist_categories": None,
    "sequence_length": 4,
    "additional_features_size": 4
}

In [38]:
model_training_args

{'lm_path': 'Epidot/TwitchLeagueBert-1000k',
 'window_size': 2,
 'num_dist_steps': None,
 'num_dist_categories': None,
 'sequence_length': 4,
 'additional_features_size': 4}

In [39]:
model = LanguageModelPlusTemporal(**model_training_args)

Some weights of the model checkpoint at Epidot/TwitchLeagueBert-1000k were not used when initializing RobertaModel: ['lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at Epidot/TwitchLeagueBert-1000k and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference

In [40]:
model.load_state_dict(model_state_dict)

<All keys matched successfully>

In [41]:
tokenizer = RobertaTokenizerFast.from_pretrained("Epidot/roberta-base-finetuned-highlight-detection")

In [42]:
md = model.to(device)

In [43]:
model

LanguageModelPlusTemporal(
  (l1): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50000, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerN

## Load huggingface model

In [ ]:
m_name = "TwitchLeagueBert-1000k-likefu"
m = models_datasets[m_name]

In [ ]:
model = RobertaForSequenceClassification.from_pretrained(m["model_name"])

Downloading:   0%|          | 0.00/812 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/313M [00:00<?, ?B/s]

In [ ]:
tokenizer = RobertaTokenizerFast.from_pretrained(m["model_name"])

Downloading:   0%|          | 0.00/479 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/760k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/429k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.97M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [ ]:
md = model.to(device)

# Eval loop

In [44]:
dataset = datasets.load_dataset(m["dataset_name"], use_auth_token=HUB_TOKEN)

Downloading:   0%|          | 0.00/1.97k [00:00<?, ?B/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/Epidot___parquet/Epidot--private_fuetal2017_highlights_temporal_preprocessed_TwitchLeagueBert-1000k_oversampled-2b7f4318013ea0d2/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [45]:
dataset

DatasetDict({
    test: Dataset({
        features: ['highlights', 'input_ids', 'attention_mask', 'message_density_scaled', 'highlights_raw', 'hl_labels', 'additional_features'],
        num_rows: 34046
    })
    train: Dataset({
        features: ['highlights', 'input_ids', 'attention_mask', 'message_density_scaled', 'highlights_raw', 'hl_labels', 'additional_features'],
        num_rows: 215089
    })
    val: Dataset({
        features: ['highlights', 'input_ids', 'attention_mask', 'message_density_scaled', 'highlights_raw', 'hl_labels', 'additional_features'],
        num_rows: 33160
    })
})

In [46]:
dataset["train"]["message_density_scaled"][:10]

[[0.07703433942685037,
  0.09303610404692839,
  0.10949857085401722,
  0.12172137807657117],
 [-0.3530384202501747,
  -0.3465261336113066,
  -0.3360177814461068,
  -0.3278989837301892],
 [1.0637857479142403,
  1.0684952588461976,
  1.071594439278565,
  1.0744798831293907],
 [3.194437008870388,
  3.196642522581379,
  3.1997714949413534,
  3.2018545610966793],
 [1.6662138182648223,
  1.6427168035565913,
  1.6216293115529063,
  1.6057439675243916],
 [0.9489142879205341,
  0.9489142879205341,
  0.9489142879205341,
  0.9489142879205341],
 [0.21652488932243358,
  0.22080259467963764,
  0.2249402610024545,
  0.22778564758548017],
 [-0.1362733289259436,
  -0.14356080229126775,
  -0.1472384169681468,
  -0.14749861802393782],
 [0.37398852242953434,
  0.2859501419608995,
  0.18663286385530367,
  0.12701740863339758],
 [0.3325559744155199,
  0.34464394328780074,
  0.36085990183287675,
  0.37556557338827845]]

In [47]:
gold_lens = [len(x) for x in dataset["train"]["highlights_raw"]]

In [48]:
activation_function = m["activation_function"]

In [49]:
def make_batches(arr, batch_size=8):
  ret = list()
  if len(arr) == batch_size:
    return arr
  for i, j in zip(range(0,len(arr)-batch_size, batch_size), range(batch_size, len(arr), batch_size)):
    ret.append(arr[i:j])

  # last batch
  remainder = len(arr) % batch_size
  if remainder != 0:
    ret.append(arr[-remainder:])
  else:
    ret.append(arr[-batch_size:])
  return ret

In [50]:
def predict_plus_temporal(m, ds, act_fct=activation_function, batch_size=8, pad_to=128):
  
  # pad sequences 
  input_ids = [(iid + [tokenizer.pad_token_id] * pad_to)[:pad_to] for iid in  ds['input_ids']]
  attention_mask = [(atm + [0] * pad_to)[:pad_to] for atm in ds['attention_mask']]
  
  additional_features = None
  if "additional_features" in ds.features:
    additional_features = ds['additional_features']

  
  # create eval batches
  input_ids_batched = [torch.IntTensor(elm).to(device) for elm in make_batches(input_ids, batch_size)]
  attention_mask_batched = [torch.IntTensor(elm).to(device) for elm in make_batches(attention_mask, batch_size)]
  additional_features_batched = None
  if additional_features:
    additional_features_batched = [torch.IntTensor(elm).to(device) for elm in make_batches(additional_features, batch_size)]    

  preds = list()
  m.eval()
  
  if additional_features_batched:
    with torch.no_grad():
      for i in tqdm(range(len(input_ids_batched))):
        iids, atm, add_ft = input_ids_batched[i], attention_mask_batched[i], additional_features_batched[i]
        preds.append(m.forward(iids, atm, add_ft))
  else:
    with torch.no_grad():
      for i in tqdm(range(len(input_ids_batched))):
        iids, atm = input_ids_batched[i], attention_mask_batched[i]
        preds.append(m.forward(iids, atm))

  if "hl_labels" in ds.features:
    targets = np.ravel(ds["hl_labels"])
  else:
    targets = np.ravel(ds["labels"])

  l_preds = [p["logits"].tolist() for p in preds]
  predictions = np.asarray([p for l in l_preds for p in l])
  predictions_scaled = np.round(activation_function(predictions))

  return predictions_scaled, targets

In [80]:
gold_ds = "test"
test_set = dataset[gold_ds] # .select(range(130))

In [81]:
preds, golds = predict_plus_temporal(model, test_set)

100%|██████████| 4256/4256 [02:27<00:00, 28.84it/s]


In [82]:
# list(zip(tokenizer.batch_decode(test_set[:5]["input_ids"]), test_set[:5]["labels"], preds[:5]))

In [83]:
len(preds), len(golds)

(34046, 68092)

In [84]:
precision_recall_fscore_support(preds.reshape(-1, 1), np.asarray(golds).reshape(-1,1), average=None, pos_label=1)

(array([0.87887689, 0.55799158]),
 array([0.91845579, 0.44850917]),
 array([0.89823056, 0.49729588]),
 array([55381, 12711]))

In [85]:
accuracy_score(np.round(preds).reshape(-1, 1), np.asarray(golds).reshape(-1,1))

0.8307290136873642

In [86]:
sum(preds), len(preds)

(array([6385., 6326.]), 34046)

In [87]:
sum(golds), len(golds)

(10217.0, 68092)

In [88]:
with open(f"/content/gdrive/MyDrive/Master Thesis/ModelFineTuning/results/{m_name}_on_{gold_ds}.json", "w") as out_file:
  json.dump({"gold": golds.tolist(), "pred":preds.tolist()}, out_file)

In [89]:
print(m_name)

TwitchLeagueBert-1000k-temporal-structure


In [90]:
ds_predictions = datasets.Dataset.from_dict({"pred": preds, "gold_raw": dataset[gold_ds]["highlights_raw"]})

In [91]:
ds_predictions

Dataset({
    features: ['pred', 'gold_raw'],
    num_rows: 34046
})

### expand prediction to frame level granularity

In [92]:
def hl_chunks_to_frames(example, context_size, pred_label, gold_label):
  ret_expanded = list()
  ret_reduced = list()
  for label, raw in zip(example[pred_label], example[gold_label][context_size[0]:-context_size[1]]):
    ret_expanded.append([label] * len(raw))
    ret_reduced.append(raw)
  return {f"{pred_label}_expanded": ret_expanded,
          f"{gold_label}_reduced": ret_reduced}

In [93]:
ch_to_fr_args = {"context_size": (1,1),
                 "pred_label": "pred",
                 "gold_label": "gold_raw"
}

In [94]:
ds_predictions_expanded = ds_predictions.map(hl_chunks_to_frames, fn_kwargs=ch_to_fr_args)

  0%|          | 0/34046 [00:00<?, ?ex/s]

In [95]:
ds_predictions_expanded

Dataset({
    features: ['pred', 'gold_raw', 'pred_expanded', 'gold_raw_reduced'],
    num_rows: 34046
})

In [96]:
pred_exp = [elm for l in ds_predictions_expanded["pred_expanded"] for e in l for elm in e]

In [97]:
gold_red = [elm for l in ds_predictions_expanded["gold_raw_reduced"] for e in l for elm in e]

In [98]:
pred_exp = np.asarray(pred_exp)
gold_red = np.asarray(gold_red)

In [99]:
pred_exp.shape, gold_red.shape

((3984080,), (3984080,))

In [100]:
precision_recall_fscore_support(gold_red, pred_exp)

(array([0.93320915, 0.42907291]),
 array([0.92483723, 0.46044952]),
 array([0.92900433, 0.44420783]),
 array([3548725,  435355]))

In [101]:
accuracy_score(gold_red, pred_exp)

0.8740918857051063

# Eval loop revert to frame level

In [73]:
dataset = datasets.load_dataset(m["dataset_name"], use_auth_token=HUB_TOKEN)

  0%|          | 0/3 [00:00<?, ?it/s]

In [74]:
dataset

DatasetDict({
    test: Dataset({
        features: ['highlights', 'input_ids', 'attention_mask', 'message_density_scaled', 'highlights_raw', 'hl_labels', 'additional_features'],
        num_rows: 34046
    })
    train: Dataset({
        features: ['highlights', 'input_ids', 'attention_mask', 'message_density_scaled', 'highlights_raw', 'hl_labels', 'additional_features'],
        num_rows: 215089
    })
    val: Dataset({
        features: ['highlights', 'input_ids', 'attention_mask', 'message_density_scaled', 'highlights_raw', 'hl_labels', 'additional_features'],
        num_rows: 33160
    })
})

In [75]:
dataset["train"]["hl_labels"]

[[0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [1.0, 1.0],
 [0.0, 0.0],
 [0.0, 0.0],

In [76]:
dataset["train"][2]["highlights_raw"]

[[1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1]]

In [77]:
def hl_chunks_to_frames(example, context_size, pred_label, gold_label):
  ret_expanded = list()
  ret_reduced = list()
  for label, raw in zip(example[pred_label], example[gold_label][context_size[0]:-context_size[1]]):
    ret_expanded.append([label] * len(raw))
    ret_reduced.append(raw)
  return {f"{pred_label}_expanded": ret_expanded,
          f"{gold_label}_reduced": ret_reduced}

In [78]:
ch_to_fr_args = {"context_size": (1,1),
                 "pred_label": "hl_labels",
                 "gold_label": "highlights_raw"
}

In [79]:
dataset_expanded = dataset.map(hl_chunks_to_frames, fn_kwargs=ch_to_fr_args)

  0%|          | 0/34046 [00:00<?, ?ex/s]

  0%|          | 0/215089 [00:00<?, ?ex/s]

KeyboardInterrupt: ignored

In [ ]:
"""
def reduce_highlights(example, context_size):
  return {"hl_raw_reduced": example["highlights_raw"][context_size[0]:-context_size[1]]}
"""

In [ ]:
# dataset_expanded_reduced = dataset_expanded.map(reduce_highlights, fn_kwargs={"context_size": (1,1)})

In [ ]:
compressed = [elm for l in dataset_expanded["train"]["hl_labels_expanded"] for e in l for elm in e]

In [ ]:
compressed = np.asarray(compressed)

In [ ]:
compressed.shape

In [ ]:
actual = [elm for l in dataset_expanded["train"]["highlights_raw_reduced"] for e in l for elm in e]

In [ ]:
actual = np.asarray(actual)

In [ ]:
actual[:10]

In [ ]:
actual.shape

In [ ]:
precision_recall_fscore_support(actual.reshape(-1,1), compressed.reshape(-1,1))

In [ ]:
accuracy_score(actual, compressed)

In [ ]:
pearsonr(actual, compressed)